version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # 将主机的80端口映射到容器的80端口
    depends_on:
      - backend  # 确保后端服务启动后再启动前端
    networks:
      - app-network

  backend:
    image: node:16.13.2-alpine
    working_dir: /app/serve
    volumes:
      - ./serve:/app/serve  # 挂载后端项目文件夹，便于开发时同步
    command: nodemon ./index.js  # 启动后端服务
    ports:
      - "3000:3000"  # 将主机的3000端口映射到容器的3000端口
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
