name: docker-build

on:
  workflow_dispatch:  # 这个触发器允许手动运行工作流
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为 Runner，但使用 CentOS Docker 容器进行构建

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Build Docker Image
        run: |
          docker build -t zhza4/game-team-system:latest --build-arg BASE_IMAGE=centos:7 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

      - name: Push Docker Image
        run: |
          docker push zhza4/game-team-system:latest

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host to Known Hosts
        run: |
          ssh-keyscan -H 47.121.188.207 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh root@47.121.188.207 "docker pull zhza4/game-team-system:latest && docker stop game-team && docker rm game-team && docker run -d -p 8084:80 -e --name game-team zhza4/game-team-system:latest"